<?php
namespace app\common\controller;
use think\Controller;
use think\Session;

class Base extends Controller
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        if (Session::get('admin') == null)
            $this->redirect('/admin/user/index');
    }
}